from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.school_dashboard, name='school_dashboard'),
    path('subject-statistics/', views.school_subject_statistics, name='school_subject_statistics'),
    path('dtr/upload/', views.school_dtr_upload, name='school_dtr_upload'),
    path('dtr/upload/template/', views.download_dtr_upload_template, name='download_dtr_upload_template'),
    path('dtr/download/<int:year>/<int:month>/', views.download_dtr_pdf, name='download_dtr_pdf'),
    path('dtr/status/<int:year>/<int:month>/', views.dtr_status, name='dtr_status'),
    path('dtr/view/<int:teacher_id>/<int:year>/<int:month>/', views.view_employee_dtr, name='view_employee_dtr'),
    path('dtr/delete/<int:year>/<int:month>/', views.delete_dtr_month, name='delete_dtr_month'),
    path('dtr/calendar/add/', views.add_dtr_calendar_exception, name='add_dtr_calendar_exception'),
    path('dtr/calendar/<int:exception_id>/remove/', views.remove_dtr_calendar_exception, name='remove_dtr_calendar_exception'),
    path('students/', views.school_student_list, name='school_student_list'),
    path('sections/', views.school_sections, name='school_sections'),
    path('sections/<int:section_id>/students/', views.school_section_students, name='school_section_students'),
    path('sections/<int:section_id>/reassign/', views.reassign_section_adviser, name='reassign_section_adviser'),
    path('sections/<int:section_id>/delete/', views.delete_section, name='delete_section'),
    path('accounts/', views.school_accounts, name='school_accounts'),
    path('accounts/<int:teacher_id>/toggle-active/', views.toggle_teacher_active, name='toggle_teacher_active'),
    path('accounts/<int:teacher_id>/toggle-officer/', views.toggle_teacher_officer, name='toggle_teacher_officer'),
    path('accounts/<int:teacher_id>/reassign-section/', views.reassign_teacher_section, name='reassign_teacher_section'),
    path('assignments/', views.school_assignments, name='school_assignments'),
    path('assignments/<int:assignment_id>/remove/', views.remove_teacher_subject_assignment, name='remove_teacher_subject_assignment'),
    path('my-assignments/', views.adviser_subject_assignments, name='adviser_subject_assignments'),
    path('my-assignments/<int:assignment_id>/remove/', views.remove_adviser_subject_assignment, name='remove_adviser_subject_assignment'),
    path('my-section/edit/', views.edit_my_section, name='edit_my_section'),
    path('profile/edit/', views.edit_school_profile, name='edit_school_profile'),
    path('scheduling/', views.school_scheduling, name='school_scheduling'),
    path('scheduling/roster/add/', views.add_schedule_roster, name='add_schedule_roster'),
    path('scheduling/cell/save/', views.save_schedule_cell, name='save_schedule_cell'),
    path('scheduling/auto-generate/', views.auto_generate_schedule, name='auto_generate_schedule'),
    path('scheduling/clear-section/', views.clear_section_schedule, name='clear_section_schedule'),
    path('scheduling/requirement/save/', views.save_schedule_requirement, name='save_schedule_requirement'),
]
