# Generated by Django 6.0.7 on 2026-08-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_studentaccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
