# Generated by Django 6.0.7 on 2026-08-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAIConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(unique=True)),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek')], default='deepseek', max_length=30)),
                ('encrypted_api_key', models.TextField()),
                ('consented_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lesson_planning_teacher_ai_connection',
            },
        ),
    ]
