# Generated by Django 6.0.7 on 2026-08-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheraiconnection',
            name='provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('openrouter', 'OpenRouter (free)')], default='deepseek', max_length=30),
        ),
    ]
