# Generated by Django 6.0.7 on 2026-08-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planning', '0002_alter_teacheraiconnection_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheraiconnection',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini (free)'), ('deepseek', 'DeepSeek'), ('openrouter', 'OpenRouter (free)')], default='gemini', max_length=30),
        ),
    ]
