# Generated by Django 6.0.7 on 2026-08-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_teacher_school_profile_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
