# Generated by Django 6.0.7 on 2026-08-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_teacher_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTimeRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField()),
                ('date', models.DateField()),
                ('am_arrival', models.CharField(blank=True, max_length=16, null=True)),
                ('am_departure', models.CharField(blank=True, max_length=16, null=True)),
                ('pm_arrival', models.CharField(blank=True, max_length=16, null=True)),
                ('pm_departure', models.CharField(blank=True, max_length=16, null=True)),
                ('undertime_hours', models.CharField(blank=True, max_length=16, null=True)),
                ('undertime_minutes', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'teacher_time_record',
                'unique_together': {('teacher_id', 'date')},
            },
        ),
    ]
