# Generated by Django 6.0.7 on 2026-08-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_teachertimerecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachertimerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teachertimerecord',
            name='employee_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='teachertimerecord',
            unique_together={('teacher_id', 'employee_name', 'date')},
        ),
    ]
