# Generated by Django 6.0.7 on 2026-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_hidden_fk_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='signature_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
