# Generated by Django 6.0.7 on 2026-08-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_teacher_signature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTRCalendarException',
            fields=[
                ('exception_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_profile_id', models.IntegerField()),
                ('date', models.DateField()),
                ('reason', models.CharField(choices=[('holiday', 'Holiday'), ('suspension', 'Class Suspension')], default='holiday', max_length=20)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dtr_calendar_exception',
                'unique_together': {('school_profile_id', 'date')},
            },
        ),
    ]
