# Generated by Django 6.0.7 on 2026-08-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_dtrcalendarexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
