# Generated by Django 6.0.7 on 2026-08-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_teacher_terms_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_officer',
            field=models.BooleanField(default=False),
        ),
    ]
