# Generated by Django 6.0.7 on 2026-08-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_teacher_is_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('visited_date', models.DateField()),
            ],
            options={
                'db_table': 'site_visit',
                'unique_together': {('ip_address', 'visited_date')},
            },
        ),
    ]
