# Generated by Django 6.0.7 on 2026-08-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtrcalendarexception',
            name='session',
            field=models.CharField(choices=[('whole_day', 'Whole Day'), ('am', 'Morning Only'), ('pm', 'Afternoon Only')], default='whole_day', max_length=20),
        ),
    ]
