# Generated by Django 6.0.7 on 2026-08-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_dtrcalendarexception_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMasterlistEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=150)),
                ('school_id', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'school_masterlist_entry',
                'indexes': [models.Index(fields=['region'], name='school_mast_region_59b0df_idx'), models.Index(fields=['region', 'division'], name='school_mast_region_80f90c_idx'), models.Index(fields=['region', 'division', 'municipality'], name='school_mast_region_293afb_idx'), models.Index(fields=['region', 'division', 'municipality', 'district'], name='school_mast_region_2e7221_idx')],
            },
        ),
    ]
