# Generated by Django 6.0.7 on 2026-08-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_schoolmasterlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
