# Generated by Django 6.0.7 on 2026-08-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_teacher_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertimerecord',
            name='leave_session',
            field=models.CharField(blank=True, choices=[('whole_day', 'Whole Day'), ('am', 'Morning Only'), ('pm', 'Afternoon Only')], default='whole_day', max_length=10),
        ),
        migrations.AddField(
            model_name='teachertimerecord',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('VL', 'Vacation Leave'), ('FL', 'Mandatory/Forced Leave'), ('SL', 'Sick Leave'), ('ML', 'Maternity Leave'), ('PL', 'Paternity Leave'), ('SPL', 'Special Privilege Leave'), ('SOLO', 'Solo Parent Leave'), ('STL', 'Study Leave'), ('VAWC', '10-Day VAWC Leave'), ('REHAB', 'Rehabilitation Privilege'), ('SLBW', 'Special Leave Benefits for Women'), ('CL', 'Special Emergency (Calamity) Leave'), ('AL', 'Adoption Leave'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
    ]
