# Generated by Django 6.0.7 on 2026-08-22 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_teachertimerecord_leave_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_category', models.CharField(choices=[('smartphone', 'Smartphone'), ('tablet', 'Tablet'), ('desktop', 'Desktop/Laptop')], max_length=12)),
                ('session_key', models.CharField(max_length=40)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'device_category'), name='one_session_per_device_category')],
            },
        ),
    ]
