# Generated by Django 6.0.7 on 2026-07-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_year', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=200)),
                ('school_id', models.CharField(max_length=20)),
                ('registrar_name', models.CharField(max_length=100)),
                ('registrar_designation', models.CharField(max_length=100)),
                ('guidance_counselor', models.CharField(max_length=100)),
                ('principal_name', models.CharField(max_length=100)),
                ('principal_designation', models.CharField(max_length=100)),
                ('sds_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher')),
            ],
            options={
                'db_table': 'school_profile',
            },
        ),
    ]
