# Generated by Django 6.0.7 on 2026-07-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_teacher_id_teacher_teacher_id_and_more'),
        ('students', '0001b_drop_created_by_fk_before_teacher_pk_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_level', models.CharField(max_length=10)),
                ('track', models.CharField(max_length=50)),
                ('strand', models.CharField(max_length=50)),
                ('section_name', models.CharField(max_length=50)),
                ('modality', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.schoolprofile')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('lrn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField()),
                ('school_g10', models.CharField(max_length=200)),
                ('school_address_g10', models.CharField(max_length=300)),
                ('average_g10', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completion_date_g10', models.DateField()),
                ('shs_admission_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.section')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
