# Generated by Django 6.0.7 on 2026-08-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_section_adviser_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='adviser',
        ),
        migrations.RemoveField(
            model_name='section',
            name='school_profile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='adviser',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='school_profile_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        # This AddField was missing from the original migration - Section.adviser
        # (a ForeignKey, physical column `adviser_id`) is removed just above, but
        # nothing ever re-created `adviser_id` as the plain IntegerField the
        # current model actually has. On the real database this went unnoticed
        # because the column already existed there from manual SQL (see
        # CLAUDE.md's "Migration history vs. real schema" note); a from-scratch
        # build would otherwise end up with no adviser_id column on section at
        # all. Must come after the RemoveField('section', 'adviser') above -
        # both map to the same physical column name.
        migrations.AddField(
            model_name='section',
            name='adviser_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='adviser_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='section_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='completion_date_g10',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='shs_admission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
