# Generated by Django 6.0.7 on 2026-08-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_section_adviser_remove_section_school_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='show_core_heading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='show_elective_heading',
            field=models.BooleanField(default=True),
        ),
    ]
