# Generated by Django 6.0.7 on 2026-08-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_hidden_fk_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecordAuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('student', 'Student'), ('grade', 'Grade'), ('attendance', 'Attendance')], max_length=20)),
                ('record_id', models.CharField(max_length=50)),
                ('lrn', models.CharField(max_length=12)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20)),
                ('performed_by', models.IntegerField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_record_audit_log',
                'ordering': ['-performed_at'],
            },
        ),
    ]
