# Generated by Django 6.0.7 on 2026-08-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentrecordauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('transferred', 'Transferred')], default='active', max_length=20),
        ),
    ]
