# Generated by Django 6.0.7 on 2026-08-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='enrollment_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
