# Generated by Django 6.0.7 on 2026-07-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_teacher_id_teacher_teacher_id_and_more'),
        ('students', '0002_alter_schoolprofile_created_by_section_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_level', models.CharField(max_length=10)),
                ('strand', models.CharField(max_length=50)),
                ('subject_number', models.IntegerField()),
                ('subject_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.schoolprofile')),
            ],
            options={
                'db_table': 'subject_mapping',
                'unique_together': {('school_profile', 'grade_level', 'strand', 'subject_number')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.IntegerField()),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
                ('subject_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.subjectmapping')),
            ],
            options={
                'db_table': 'grades',
                'unique_together': {('student', 'subject_mapping', 'term')},
            },
        ),
    ]
