# Generated by Django 6.0.7 on 2026-08-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_teachersubjectassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subjectmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lrn',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='lrn',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='mapping_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmapping',
            name='school_profile_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='uploaded_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='uploaded_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjectmapping',
            name='created_by',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject_mapping',
        ),
        migrations.RemoveField(
            model_name='subjectmapping',
            name='school_profile',
        ),
    ]
