# Generated by Django 6.0.7 on 2026-08-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTermExclusion',
            fields=[
                ('exclusion_id', models.AutoField(primary_key=True, serialize=False)),
                ('mapping_id', models.IntegerField()),
                ('term', models.IntegerField()),
                ('excluded_by', models.IntegerField()),
                ('excluded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subject_term_exclusion',
                'unique_together': {('mapping_id', 'term')},
            },
        ),
    ]
