# Generated by Django 6.0.7 on 2026-08-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_subjecttermexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermRemark',
            fields=[
                ('remark_id', models.AutoField(primary_key=True, serialize=False)),
                ('lrn', models.CharField(max_length=12)),
                ('term', models.IntegerField()),
                ('remark', models.TextField(blank=True, default='')),
                ('updated_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_term_remark',
                'unique_together': {('lrn', 'term')},
            },
        ),
    ]
