# Generated by Django 6.0.7 on 2026-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_studenttermremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmapping',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
