# Generated by Django 6.0.7 on 2026-08-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_backfill_is_elective'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='final_exam_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='pretest_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
