# Generated by Django 6.0.7 on 2026-08-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0010_grade_final_exam_score_grade_pretest_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTestMaxScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('term', models.IntegerField()),
                ('pretest_max', models.IntegerField(blank=True, null=True)),
                ('final_exam_max', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subject_test_max_scores',
                'unique_together': {('assignment_id', 'term')},
            },
        ),
    ]
