# Generated by Django 6.0.7 on 2026-08-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0011_subjecttestmaxscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttestmaxscore',
            name='final_exam_llc_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjecttestmaxscore',
            name='final_exam_llc_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjecttestmaxscore',
            name='final_exam_llc_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjecttestmaxscore',
            name='pretest_llc_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjecttestmaxscore',
            name='pretest_llc_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjecttestmaxscore',
            name='pretest_llc_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
