# Generated by Django 6.0.7 on 2026-08-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0012_subjecttestmaxscore_final_exam_llc_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='schedule_days',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='schedule_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
