# Generated by Django 6.0.7 on 2026-08-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0014_remove_teachersubjectassignment_schedule_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubjectassignment',
            name='schedule',
        ),
        migrations.AddField(
            model_name='subjecttestmaxscore',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
