# Generated by Django 6.0.7 on 2026-08-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0016_add_hidden_fk_constraints'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['lrn', 'mapping_id', 'term'], name='grades_lrn_mapping_term_idx'),
        ),
    ]
