# Generated by Django 6.0.7 on 2026-08-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0017_grade_grades_lrn_mapping_term_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_incomplete',
            field=models.BooleanField(default=False),
        ),
    ]
