# Generated by Django 6.0.7 on 2026-08-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0018_grade_is_incomplete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncillaryTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField()),
                ('task_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ancillary_task',
                'ordering': ['task_name'],
            },
        ),
        migrations.CreateModel(
            name='AncillaryTaskSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('term', models.IntegerField()),
                ('schedule', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ancillary_task_schedule',
                'unique_together': {('task_id', 'term')},
            },
        ),
    ]
