# Generated by Django 6.0.7 on 2026-08-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAccountAuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_teacher_id', models.IntegerField()),
                ('action', models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], max_length=20)),
                ('performed_by', models.IntegerField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'teacher_account_audit_log',
                'ordering': ['-performed_at'],
            },
        ),
    ]
