# Generated by Django 6.0.7 on 2026-08-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_profile_id', models.IntegerField()),
                ('section_label', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('edited', 'Edited'), ('deleted', 'Deleted')], max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('performed_by', models.IntegerField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'section_audit_log',
                'ordering': ['-performed_at'],
            },
        ),
    ]
