# Generated by Django 6.0.7 on 2026-08-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_sectionauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRequirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField(unique=True)),
                ('sessions_per_week', models.PositiveIntegerField(default=4)),
            ],
            options={
                'db_table': 'schedule_requirement',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('timeslot_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_profile_id', models.IntegerField()),
                ('slot_order', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'time_slot',
                'ordering': ['school_profile_id', 'slot_order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_profile_id', models.IntegerField()),
                ('assignment_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
                ('mapping_id', models.IntegerField()),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('timeslot_id', models.IntegerField()),
            ],
            options={
                'db_table': 'schedule_entry',
                'unique_together': {('section_id', 'day_of_week', 'timeslot_id'), ('teacher_id', 'day_of_week', 'timeslot_id')},
            },
        ),
    ]
