# Generated by Django 6.0.7 on 2026-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_schedulerequirement_timeslot_scheduleentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheraccountauditlog',
            name='action',
            field=models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated'), ('promoted_officer', 'Promoted to Officer'), ('demoted_officer', 'Demoted to Non-Officer')], max_length=20),
        ),
    ]
