# Generated by Django 6.0.7 on 2026-08-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_teacheraccountauditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_profile_id', models.IntegerField()),
                ('lrn', models.CharField(max_length=12)),
                ('surname', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('extension', models.CharField(blank=True, default='', max_length=10)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('grade_level', models.CharField(max_length=10)),
                ('track', models.CharField(blank=True, default='', max_length=50)),
                ('strand', models.CharField(blank=True, default='', max_length=50)),
                ('previous_school', models.CharField(blank=True, default='', max_length=200)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_relationship', models.CharField(blank=True, default='', max_length=50)),
                ('guardian_contact', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected'), ('other', 'Other')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('appearance_date', models.DateField(blank=True, null=True)),
                ('appearance_time', models.TimeField(blank=True, null=True)),
                ('scheduled_by', models.IntegerField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.IntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enrollment_application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_profile_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('scope_code', models.CharField(max_length=10)),
                ('assigned_by', models.IntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enrollment_assignment',
                'unique_together': {('school_profile_id', 'teacher_id', 'scope_code')},
            },
        ),
    ]
